name: binary-tagged
version: 0.1.4.0
synopsis: Tagged binary serialisation.
description: Check <https://github.com/phadej/binary-tagged#readme README on Github>
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/binary-tagged
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base                     >=4.7  && <4.10
  - aeson                    >=0.8  && <0.12
  - array                    >=0.5  && <0.6
  - binary                   >=0.7  && <0.9
  - bytestring               >=0.10 && <0.11
  - containers               >=0.5  && <0.6
  - generics-sop             >=0.1  && <0.3
  - hashable                 >=1.2  && <1.3
  - nats                     >=1    && <1.2
  - scientific               >=0.3  && <0.4
  - SHA                      >=1.6  && <1.7
  - semigroups               >=0.16 && <0.19
  - tagged                   >=0.7  && <0.9
  - text                     >=1.2  && <1.3
  - time                     >=1.4  && <1.7
  - unordered-containers     >=0.2  && <0.3
  - vector                   >=0.10 && <0.12

library:
  source-dirs: src

tests:
  binary-tagged-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary-tagged
      - binary-orphans >=0.1.1
      - bifunctors
      - quickcheck-instances
      - tasty
      - tasty-quickcheck

benchmarks:
  binary-tagged-bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
      - binary-tagged
      - binary-orphans >=0.1.1
      - deepseq
      - criterion
